{
  imports = [
    ./coding/blink-cmp.nix
    ./coding/duplicate.nix
    ./coding/edition.nix
    ./coding/leap
    ./coding/spider.nix
    ./coding/visual-multi.nix
    ./interface/bufferline.nix
    ./interface/colorschemes.nix
    ./interface/dashboard
    ./interface/gitsigns.nix
    ./interface/floating-help
    ./interface/interface.nix
    ./interface/lualine.nix
    ./interface/neo-tree
    ./interface/terminal.nix
    ./formatting
    ./lsp
    ./utils
  ];
}
