{
  imports = [
    ./coding
    ./coding/ai
    ./coding/autopairs
    ./coding/blink-cmp
    ./coding/duplicate
    ./coding/flash
    ./coding/leap
    ./coding/spider
    ./coding/text-case
    ./coding/visual-multi
    ./coding/visual-surround
    ./debugger
    ./formatting
    ./interface
    ./interface/bufferline
    ./interface/cinnamon
    ./interface/colorschemes.nix
    ./interface/dashboard
    ./interface/edgy
    ./interface/floating-help
    ./interface/gitsigns
    ./interface/lualine
    ./interface/neo-tree
    ./interface/noice
    ./interface/render-markdown
    ./interface/scroll-eof
    ./interface/scrollbar
    ./interface/sunglasses
    ./interface/treesitter
    ./interface/web-devicons
    ./lsp
    ./utils
    ./utils/arrow
    ./utils/snacks
    ./utils/toggleterm
    ./utils/which-key
  ];
}
