{
  imports = [
    ./coding/ai.nix
    ./coding/blink-cmp.nix
    ./coding/duplicate.nix
    ./coding/edition.nix
    ./coding/leap
    ./coding/text-case
    ./coding/spider.nix
    ./coding/visual-multi.nix
    ./debugger/default.nix
    ./interface/bufferline.nix
    ./interface/colorschemes.nix
    ./interface/dashboard
    ./interface/floating-help
    ./interface/gitsigns.nix
    ./interface/interface.nix
    ./interface/lualine.nix
    ./interface/neo-tree
    ./interface/treesitter
    ./formatting
    ./lsp
    ./utils
    ./utils/snacks
    ./utils/toggleterm
  ];
}
